{"name": "test_login_with_incorrect_credentils", "status": "failed", "statusDetails": {"message": "AssertionError: assert True is False", "trace": "self = <test_login_api.TestLogin object at 0x000002CBFB3330E0>\n\n>   ???\nE   assert True is False\n\nC:\\Users\\UJJIS\\PycharmProjects\\AppiumPyTestPOM\\pythonAPI_FrameWork\\TestCases\\test_login_api.py:20: AssertionError"}, "attachments": [{"name": "stdout", "source": "49632605-f5f7-44e2-9a69-8517b314797c-attachment.txt", "type": "text/plain"}], "start": 1722258520119, "stop": 1722258520553, "uuid": "b384a8a7-6f07-4e0e-8ac4-7778b4c01f0b", "historyId": "c77101d3665ed182606551763838b80a", "testCaseId": "c77101d3665ed182606551763838b80a", "fullName": "test_login_api.TestLogin#test_login_with_incorrect_credentils", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('log_on_failure')"}, {"name": "suite", "value": "test_login_api"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-BM22L539"}, {"name": "thread", "value": "75544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_api"}]}